[package]
name = "ugli_engine"
version = "0.0.12"
authors = ["KonradP <konradpodstawskii@gmail.com>"]
edition = "2018"

[dependencies]
ugli-webgl = "0.1.0"
stdweb = "0.4.20"
stdweb-derive= "0.5.3"
serde = "1.0.135"
serde_derive = "1.0.135"
futures = "0.3.19"

