[package]
name = "ugli_engine"
version = "0.0.12"
authors = ["KonradP <konradpodstawskii@gmail.com>"]
edition = "2018"

[dependencies]
ugli-webgl = "0.1.0"
stdweb = "0.4.0"
stdweb-derive= "0.4.0"
serde = "0.8.4"
serde_derive = "0.8.4"
